- pkg:nuget/ApplicationOS.APM.Monitoring.Prometheus@1.0.0
- pkg:nuget/ApplicationOS.APM.Monitoring.Prometheus@1.0.1
- pkg:nuget/ApplicationOS.APM.Monitoring.Prometheus@1.0.2
- pkg:nuget/ApplicationOS.APM.Monitoring.Prometheus@1.0.3
- pkg:nuget/ApplicationOS.APM.Monitoring.Prometheus@1.0.4
